#本配置文件路径
#"./xcbbrobot/config/config.yaml"

#日志等级描述
#    L_OFF   : 0
#    L_FATAL : 1
#    L_ERROR : 2
#    L_WARN  : 3
#    L_INFO  : 4
#    L_DEBUG : 5

#机器人列表文件路径
Robotlist: "../src/xcbbrobot/robotvector/robot.list"


